### ISSUE TITLE
Go through the register for the one-chamber book from 1973-1993/1994

### ISSUE THREAD

**Issue by MansMeg** [salgo60/Wikidata_riksdagen-corpus#95]
Hi!

We were thinking of going through the one chamber book from 1973-1993/1994 in a similar way as https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt . Is there a reason why this has not been done? Just curios to know before we start?

**Comment by salgo60** [comment]
I guess its because that ["Riksdagens Öppna data" is available from 1990](https://data.riksdagen.se/data/ledamoter/)

@Ainali @miroli @SchermanJ any other thoughts?

FYI @MansMeg 
* I guess @Ainali is the one who is updating Wikidata most with new people / [Ainali latest WD updates](https://www.wikidata.org/w/index.php?title=Special:Contributions/Ainali&target=Ainali&offset=&limit=500) / 
   * my understanding is that for "new" Swedish PMs are added like below [Q116866668](https://www.wikidata.org/wiki/Q116866668?uselang=sv#P39)

   [<img width="1354" alt="image" src="https://user-images.githubusercontent.com/14206509/227000368-fa4bac3f-4c4f-43b4-82ac-73a9b995ca08.png">](https://www.wikidata.org/wiki/Q116866668?uselang=sv#P39)

**Comment by MansMeg** [comment]
Ok. Great. Then we will probably take a pass also on the register of the one-chamber book to double check that all are included.

**Comment by salgo60** [comment]
Another reason can be that we didnt have the books mentioned in [#147](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/147)
